FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  Login.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/Login.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  Login.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/Login.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  Login.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/Login.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  Login.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/Login.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  Login.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/Login.py
